spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true # ?? ??? ???. ??? ?? ???? ??
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    mysql:
      url: jdbc:mysql://localhost:3306/image_test
      username: root
      password: 7845120qwe
      driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    path match:
      matching-strategy: ant_path_matcher

# AWS ?? ??
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID:your-access-key} # ?? ??? ?? ??
      secretKey: ${AWS_SECRET_ACCESS_KEY:your-secret-key} # ?? ??? ?? ??
    region:
      static: ${AWS_REGION:your-region} # ?: us-east-1

# S3 ?? ?? ??
app:
  aws:
    s3:
      bucketName: ${S3_BUCKET_NAME:your-bucket-name}
