spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true # ?? ??? ???. ??? ?? ???? ??
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    mysql:
      url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:image_test}
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:7845120qwe}
      driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    path match:
      matching-strategy: ant_path_matcher