app:
  domainUrl: http://${DOMAIN:HOST}:${PORT:PORT}

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  datasource:
    url: jdbc:mysql://${DOMAIN:HOST}:${PORT:3306}/${DATABASE_NAME:YOUR_DATABASE}
    username: ${YOUR_NAME:DB_USER}
    password: ${YOUR_PASSWORD:DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client-id:YOUR_CLIENT_ID}
            client-secret: ${client-secret:YOUR_CLIENT_SECRET}
            scope:
              - profile
              - email
  mvc:
    path match:
      matching-strategy: ant_path_matcher

jwt:
  secretKey: ${secretKey:SeCrEtKeY4HaShInG}
  access:
    expiration: ${accessTokenExpirationPeriod:3600000}
  refresh:
    expiration: ${refreshTokenExpirationPeriod:1209600000}

aws:
  ses:
    access-key: ${accessKey:YOUR_ACCESS_KEY}
    secret-key: ${secretKey:YOUR_SECRET_KEY}
    sender-email: ${senderEmail:YOUR_SENDER_EMAIL}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID:your-access-key} # ?? ??? ?? ??
      secretKey: ${AWS_SECRET_ACCESS_KEY:your-secret-key} # ?? ??? ?? ??
    region:
      static: ${AWS_REGION:your-region} # ?: us-east-1
    ses:
      access-key: ${accessKey:YOUR_ACCESS_KEY}
      secret-key: ${secretKey:YOUR_SECRET_KEY}
      sender-email: ${senderEmail:YOUR_SENDER_EMAIL}
    s3:
      bucketName: ${S3_BUCKET_NAME:your-bucket-name}


azure:
  formrecognizer:
    endpoint: ${AZURE_OCR_ENDPOINT:https://${OCR_GROUP:YOUR_OCR_GROUP}.cognitiveservices.azure.com/}
    apikey: ${AZURE_OCR_KEY:YOUR_AZURE_OCR_KEY}

invite:
  link:
    length: ${INVITE_LINK_LENGTH:10}
    characters:
      - ${CHARACTERS:ABCDEFGHIJKLMNOPQRSTUVWXYZ}
      - ${CHARACTERS:abcdefghijklmnopqrstuvwxyz}
      - ${CHARACTERS:0123456789}
