spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true # ?? ??? ???. ??? ?? ???? ??
    database-platform: H2
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client-id:YOUR_CLIENT_ID}
            client-secret: ${client-secret:YOUR_CLIENT_SECRET}
            scope:
              - profile
              - email

  mvc:
    path match:
      matching-strategy: ant_path_matcher

jwt:
  secretKey: ${secretKey:SeCrEtKeY4HaShInG}
  access:
    expiration: ${accessTokenExpirationPeriod:3600000}
  refresh:
    expiration: ${refreshTokenExpirationPeriod:1209600000}